import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import Card from "../components/Card.jsx";
import { fetchMetrics } from "../api.js";
import { prettyDriver } from "../labels.js";

// Metrics shown as grouped bars in the model-comparison chart.
const METRIC_KEYS = ["Precision", "Recall", "F1", "ROC-AUC", "PR-AUC"];
const METRIC_COLORS = ["#2563eb", "#7c3aed", "#0891b2", "#16a34a", "#d97706"];

export default function Dashboard() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchMetrics().then(setData).catch((e) => setError(e.message));
  }, []);

  if (error) return <ErrorBox message={error} />;
  if (!data) return <p className="text-slate-500">Loading metrics…</p>;

  const { summary, model_comparison } = data;

  // Top churn drivers come from summary.json as { encoded_name: mean|SHAP| }.
  const drivers = Object.entries(summary.top_drivers || {})
    .map(([name, value]) => ({ name: prettyDriver(name), value: Number(value) }))
    .slice(0, 10);

  return (
    <div className="space-y-6">
      {/* Headline stats */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <Stat label="Customers analysed" value={summary.n_customers?.toLocaleString()} />
        <Stat label="Churn rate" value={`${(summary.churn_rate * 100).toFixed(1)}%`} />
        <Stat label="Best model" value={summary.best_model} />
      </div>

      {/* How it was trained — methodology panel, readable in-app by the examiner */}
      <HowItWasTrained summary={summary} comparison={model_comparison} />

      {/* Model comparison chart */}
      <Card title="Model comparison (test set)">
        <ResponsiveContainer width="100%" height={320}>
          <BarChart data={model_comparison} margin={{ top: 10, right: 10, bottom: 30, left: 0 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} />
            <XAxis dataKey="Model" tick={{ fontSize: 11 }} interval={0} angle={-12} dy={10} />
            <YAxis domain={[0, 1]} tick={{ fontSize: 11 }} />
            <Tooltip />
            <Legend wrapperStyle={{ fontSize: 12 }} />
            {METRIC_KEYS.map((key, i) => (
              <Bar key={key} dataKey={key} fill={METRIC_COLORS[i]} radius={[2, 2, 0, 0]} />
            ))}
          </BarChart>
        </ResponsiveContainer>
        <p className="mt-2 text-xs text-slate-500">
          All ML models are compared against a rule-based baseline. The best model
          (by F1) is highlighted in the headline above.
        </p>
      </Card>

      {/* Top churn drivers */}
      <Card title="Top churn drivers (mean |SHAP| from training)">
        <ResponsiveContainer width="100%" height={360}>
          <BarChart layout="vertical" data={drivers} margin={{ left: 40, right: 20 }}>
            <CartesianGrid strokeDasharray="3 3" horizontal={false} />
            <XAxis type="number" tick={{ fontSize: 11 }} />
            <YAxis type="category" dataKey="name" width={180} tick={{ fontSize: 11 }} />
            <Tooltip formatter={(v) => Number(v).toFixed(3)} />
            <Bar dataKey="value" radius={[0, 3, 3, 0]}>
              {drivers.map((_, i) => (
                <Cell key={i} fill="#dc2626" />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
        <p className="mt-2 text-xs text-slate-500">
          These are the features that most influence churn predictions overall.
          Per-customer drivers are shown on the “Predict a customer” screen.
        </p>
      </Card>

      {/* Pre-rendered report charts (generated by src/train.py) */}
      <Card title="Report charts (from training)">
        <p className="mb-3 text-xs text-slate-500">
          Static charts produced offline by <code>src/train.py</code> and saved in
          <code> outputs/</code>. Use these directly in your report.
        </p>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <ReportImage name="confusion_matrix.png" caption="Confusion matrix (best model)" />
          <ReportImage name="roc_curves.png" caption="ROC curves" />
          <ReportImage name="pr_curves.png" caption="Precision-Recall curves" />
          <ReportImage name="shap_bar.png" caption="SHAP feature importance" />
        </div>
      </Card>
    </div>
  );
}

// "How it was trained" — a compact methodology summary the examiner can read in the
// app, sourced from summary.json + model_comparison.csv (via /metrics). Numbers come
// straight from the data, not hard-coded, so they always match the latest train.py run.
function HowItWasTrained({ summary, comparison }) {
  const metricKeys = ["Precision", "Recall", "F1", "ROC-AUC", "PR-AUC"];
  const models = comparison.map((r) => r.Model);

  // Highlight the winning model row (matches summary.best_model).
  const isBest = (name) => name === summary.best_model;

  return (
    <Card title="How it was trained (methodology)">
      <ul className="mb-4 grid grid-cols-1 gap-x-6 gap-y-1 text-sm text-slate-600 sm:grid-cols-2">
        <li>• <strong>{summary.n_customers?.toLocaleString()}</strong> customers in the dataset (Telco Customer Churn).</li>
        <li>• Churn rate ≈ <strong>{(summary.churn_rate * 100).toFixed(1)}%</strong> (class-imbalanced).</li>
        <li>• <strong>80 / 20</strong> stratified train/test split — metrics below are on the held-out 20% (<strong>unseen</strong> data).</li>
        <li>• Class imbalance handled with balanced class weights.</li>
        <li>• Models compared: <strong>{models.join(", ")}</strong>.</li>
        <li>• Winning model (by F1): <strong>{summary.best_model}</strong>.</li>
      </ul>

      <div className="overflow-x-auto">
        <table className="min-w-full text-left text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-slate-500">
              <th className="px-3 py-2 font-semibold">Model</th>
              {metricKeys.map((k) => (
                <th key={k} className="px-3 py-2 text-right font-semibold">{k}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {comparison.map((row) => (
              <tr
                key={row.Model}
                className={`border-b border-slate-100 ${isBest(row.Model) ? "bg-green-50 font-medium" : ""}`}
              >
                <td className="px-3 py-2 text-slate-700">
                  {row.Model}
                  {isBest(row.Model) && <span className="ml-2 text-xs text-green-700">★ best</span>}
                </td>
                {metricKeys.map((k) => (
                  <td key={k} className="px-3 py-2 text-right tabular-nums text-slate-600">
                    {Number(row[k]).toFixed(3)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="mt-2 text-xs text-slate-500">
        Metrics are generated by <code>src/train.py</code> and read live from{" "}
        <code>/metrics</code>. F1 is the headline metric because the classes are imbalanced.
      </p>
    </Card>
  );
}

function Stat({ label, value }) {
  return (
    <Card>
      <p className="text-sm text-slate-500">{label}</p>
      <p className="mt-1 text-2xl font-bold text-slate-900">{value ?? "—"}</p>
    </Card>
  );
}

// Report PNGs are served by the backend as static files at /outputs/<name>.
function ReportImage({ name, caption }) {
  const base = import.meta.env.VITE_API_URL || "/api";
  return (
    <figure className="overflow-hidden rounded-lg border border-slate-200">
      <img src={`${base}/outputs/${name}`} alt={caption} className="w-full" loading="lazy" />
      <figcaption className="bg-slate-50 px-3 py-2 text-xs text-slate-500">{caption}</figcaption>
    </figure>
  );
}

function ErrorBox({ message }) {
  return (
    <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">
      <p className="font-semibold">Could not load metrics.</p>
      <p className="mt-1">{message}</p>
      <p className="mt-2 text-red-600">
        Is the backend running, and have you run <code>python src/train.py</code> to
        generate <code>outputs/</code>?
      </p>
    </div>
  );
}
